import 'package:flutter/material.dart';

import '../models/instrument_model.dart';

final instrumentList = <InstrumentModel>[
  InstrumentModel(
    brand: 'Gibson',
    instrumentImage: 'assets/images/guitar_images/less_paul_home.png',
    description: 'description',
    season: "50's",
    number: 'number',
    type: InstumentType.string,
    colour: const Color(0x00000FFF),
    model: 'Les Paul',
    instrumentGalleryImages: ['instrumentGalleryImages'],
  ),
  InstrumentModel(
    brand: 'Gibson',
    instrumentImage: 'assets/images/guitar_images/less_paul_home.png',
    description: 'description',
    season: "50's",
    number: 'number',
    type: InstumentType.string,
    colour: const Color(0x00000FFF),
    model: 'Les Paul',
    instrumentGalleryImages: ['instrumentGalleryImages'],
  ),
  InstrumentModel(
    brand: 'Gibson',
    instrumentImage: 'assets/images/guitar_images/less_paul_home.png',
    description: 'description',
    season: "50's",
    number: 'number',
    type: InstumentType.string,
    colour: const Color(0x00000FFF),
    model: 'Les Paul',
    instrumentGalleryImages: ['instrumentGalleryImages'],
  ),
  InstrumentModel(
    brand: 'Gibson',
    instrumentImage: 'assets/images/guitar_images/less_paul_home.png',
    description: 'description',
    season: "50's",
    number: 'number',
    type: InstumentType.string,
    colour: const Color(0x00000FFF),
    model: 'Les Paul',
    instrumentGalleryImages: ['instrumentGalleryImages'],
  ),
  InstrumentModel(
    brand: 'Gibson',
    instrumentImage: 'assets/images/guitar_images/less_paul_home.png',
    description: 'description',
    season: "50's",
    number: 'number',
    type: InstumentType.string,
    colour: const Color(0x00000FFF),
    model: 'Les Paul',
    instrumentGalleryImages: ['instrumentGalleryImages'],
  ),
];
